MCP 2180: Documents unavailable for review
department-of-veterans-affairs/abd-vro pull request #1009
Opened 2023-01-27 22:14 UTC by jbregstone

## What was the problem?

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-01-31 02:44 UTC, dimitri-amida reviewed
I have some comments about potential PII. This is still WIP and failing tests, so it will need another pass.

2023-01-31 02:44 UTC, dimitri-amida commented on service-python/assessclaimdc7101/src/lib/queues.py
> +    logging.info(message)
Do we know this has no PII?

2023-01-31 02:44 UTC, dimitri-amida commented on service-python/pdfgenerator/src/lib/queues.py
> +        logging.info(f" Received message: {message}")
PII?

2023-01-31 02:44 UTC, dimitri-amida commented on shared/domain/src/main/java/gov/va/vro/model/mas/MasAutomatedClaimPayload.java
> +   * Get diagnostic code.
Not necessary for a method called getDiagnosticCode

2023-02-02 20:08 UTC, jbregstone commented on service-python/assessclaimdc7101/src/lib/queues.py
> +    logging.info(message)
I need to remove this

2023-02-03 17:54 UTC, jbregstone commented on service-python/pdfgenerator/src/lib/queues.py
> +        logging.info(f" Received message: {message}")
Need to be deleted or commented

2023-02-06 15:48 UTC, jbregstone commented
> No issues building/generating PDF. Did you have a ICN that has unavailable documents?

Unfortunately I do not know of a test veteran that we can use to test the end to end integration of this feature. We may have to earmark it for now. My understanding is that there are ongoing discussions on the test veterans we have access to.

2023-02-09 23:48 UTC, jbregstone commented
#811

2023-02-22 13:33 UTC, au2 requested changes
This does not really work. I pushed an example in end to end test which uses mock collection id'ed 376.  Looking at the Java code.

2023-02-22 14:33 UTC, rajesh-Krishnasamy approved these changes

2023-02-22 14:42 UTC, merged