Mcp 2374: remove placeholders in the pdf template
department-of-veterans-affairs/abd-vro pull request #1129
Opened 2023-02-17 16:17 UTC by jbregstone

## What was the problem?

Static placeholders for some fields were in the template. 

Associated tickets or Slack threads:

- [MCP-2374](https://amida.atlassian.net/browse/MCP-2374)

## How does this fix it?[^1]

Get more data from MAS and add it to the PDF template.

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-02-20 20:03 UTC, au2 commented
@jbregstone Can you run ./gradlew :shared:domain:spotlessApply please?

2023-02-20 22:36 UTC, au2 requested changes
I ran the end to end test (testAutomatedClaimSufficientSeparate) and sent you the output. There are still issues. I particular I still cannot tell where the data is coming from. And there are bunch of class="empty">n.a.'s

2023-02-21 15:18 UTC, wlin2019 reviewed
The Java change looks good to me. But :app:end2endtest failed. It seems that also fails in develop branch.

2023-02-21 16:47 UTC, rajesh-Krishnasamy approved these changes

2023-02-21 17:04 UTC, merged