Formate "recievedDate"
department-of-veterans-affairs/abd-vro pull request #1156
Opened 2023-02-22 19:22 UTC by jbregstone

## What was the problem?

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-02-22 20:46 UTC, alan-amida requested changes
e2eTest fails here:
https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/4246243657/jobs/7382806048#step:8:884
```
VroV1Tests > positive7101Case01() FAILED
    java.lang.AssertionError: evidence.bp_readings[0]
    Unexpected: receiptDate
     ; evidence.bp_readings[1]
    Unexpected: receiptDate
     ; evidence.bp_readings[2]
    Unexpected: receiptDate
        at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:417)
```

2023-02-22 21:19 UTC, anthonyvelazquez submitted a review, later dismissed

2023-02-22 22:22 UTC, anthonyvelazquez approved these changes

2023-02-23 00:57 UTC, alan-amida approved these changes

2023-02-23 01:58 UTC, merged