Mcp 2550 - Adjust MAS BP annotation handling
department-of-veterans-affairs/abd-vro pull request #1320
Opened 2023-03-22 17:33 UTC by wlin2019

Using regex to handling MAS BP annotation handling

## What was the problem?
For some MAS BP annotation data, VRO cannot handle it gracefully, and create some crashing error messages. See MCP-2550.

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

Using regular expression to handle the BP annotation data.

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-03-22 20:17 UTC, ianwolson approved these changes

2023-03-23 03:09 UTC, rajesh-Krishnasamy commented on service/provider/src/main/java/gov/va/vro/service/provider/mas/service/mapper/MasCollectionAnnotsResults.java
> +    if (!matcher.matches()) {
Could you please check with the business team to see whether an exception has to be raised if the BP annotation values don't match the expected format.

2023-03-23 14:23 UTC, au2 submitted a review, later dismissed
Remove LABRESULT from the cases we handle. I verified that we are not receiving those. Or any blood pressure will be send by those.

2023-03-23 15:51 UTC, wlin2019 commented
> Remove LABRESULT from the cases we handle. I verified that we are not receiving those. Or any blood pressure will be send by those.

Removed.

2023-03-24 01:15 UTC, alan-amida approved these changes
Looks good. Thanks, Warren!

2023-03-24 01:31 UTC, merged

2023-03-24 02:01 UTC, au2 requested changes