MCP-2557 PDF Generator Table Break Logic
department-of-veterans-affairs/abd-vro pull request #1321
Opened 2023-03-23 03:38 UTC by anthonyvelazquez

## What was the problem?

Currently, the template has breakpoints after each table is defined regardless of its size. The design team asked if it would be possible to keep multiple tables on 1 page if they fit properly without any overflow.

Associated tickets or Slack threads:

- [MCP-2557](https://amida.atlassian.net/browse/MCP-2557)

## How does this fix it?[^1]

Remove all the manual breakpoints and then iterate over each table and compare the heights of them to see if they fit together or not. If they don't then we add the breakpoint

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-04-19 03:23 UTC, alan-amida approved these changes
Did this one just get neglected by us, @anthonyvelazquez ?

2023-04-19 13:37 UTC, anthonyvelazquez commented
> Did this one just get neglected by us, @anthonyvelazquez ?

Not a requirement for iMVP but for after. Got the work done ahead of time but with our stable tests, I don't want to introduce something like this that might cause issues so close to go live. Will add more reviewers to get this merge after that

2023-04-24 14:36 UTC, jbregstone requested changes
Logic looks good! I could not run the template as is because it does not have a corresponding template-variable file. I would switch the new logic with the old `hypertension-v2` if this is the way designers want to go. Also I would run a sample by the design people, the tables look a little too condensed to me but I'm not a designer. (example: <img width="1412" alt="Screenshot 2023-04-24 at 10 28 05 AM" src="https://user-images.githubusercontent.com/54538359/234028710-de573024-33b0-46e8-839c-1167768a219a.png">)
Maybe adding some padding under the table before the next one would work. Another consideration is having the header for the table consistently at top of page makes the document easier to skim, just my personal opinion.

2023-04-24 14:39 UTC, jbregstone approved these changes

2023-04-24 16:18 UTC, merged