MCP-2536 Change offramp messages
department-of-veterans-affairs/abd-vro pull request #1356
Opened 2023-03-28 16:09 UTC by ianwolson

## What was the problem?
Our off-ramp slack messages are not consistent.  The earlier (pre camel) check messages have icn and claim id, later (post camel) messages do not. Earlier messages have …. [collection id = 637]…., later messages have …..collection ID:637. These should really be consistent.

Associated tickets or Slack threads:

- [MCP-2536](https://amida.atlassian.net/browse/MCP-2536)

## How does this fix it?[^1]

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-03-29 22:13 UTC, alan-amida commented
Got some conflicts.

2023-03-29 23:40 UTC, yoomlam approved these changes

2023-03-30 20:51 UTC, au2 requested changes
@ianwolson all slack messages are being sent from the same spot now. I think you already know the code because of 2580. Can you clean up these conflict and include those keys for slack messages in the messages themselves (maybe in parentheses). That way we can also improve the e2e tests to check the keys.

2023-04-03 16:25 UTC, alan-amida commented
There is one e2e error but @au2 believes it is because GH Actions are being slow. This particular failure is also appearing in PR #1394 ... will merge and be on standby if this fails in PRODTESTing.

2023-04-03 16:25 UTC, alan-amida approved these changes

2023-04-03 16:25 UTC, merged