MCP-2664 POST exam-order-slack endpoint
department-of-veterans-affairs/abd-vro pull request #1422
Opened 2023-04-05 18:39 UTC by ianwolson

## What was the problem?
We want an endpoint to trigger a process that slacks all exam orders that have not yet been processed by MAS.

Associated tickets or Slack threads:

- [MCP-2664](https://amida.atlassian.net/browse/MCP-2664)

## How does this fix it?[^1]
Creates an exam-order-slack endpoint which will slack all exam orders that have not been processed by MAS.  aka orderedAt = null.

## How to test this PR
- Run automatedClaim with benefeitClaimId = 1390 and collectionId = 390
- Verify that the audit shows in DB, and that the mock-slack container contains the correct message.

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-04-07 13:37 UTC, hayleymdawson commented on api/src/main/java/gov/va/vro/api/resources/ClaimMetricsResource.java
> +      summary = "Retrieves all exam order records",
Might want to mention slack in the summary just so people dont accidentally spam slack.

2023-04-07 13:38 UTC, hayleymdawson commented on api/src/main/java/gov/va/vro/api/resources/ClaimMetricsResource.java
> +          "This endpoint does the same as exam-order-info, but it also slacks the list of exam orders.")
Also unless it changed the other endpoint will return processed orders too and we don't want to slack those so maybe this needs to be more specific in the description?

2023-04-07 13:40 UTC, hayleymdawson requested changes
Code looks mostly clean, but one spec vs implementation difference- there's no filter on whether the status is ORDER_SUBMITTED or not (which is what VRO sets), that I see, which unless I missed it, are the only items requested? (or possibly some other status filter).

We wouldnt want to repeatedly slack things that are processed/finished.

2023-04-14 20:36 UTC, au2 requested changes
I would wait Julian's PR #1446 to finalize this.

2023-04-18 16:29 UTC, au2 requested changes
Some inline comments. Please address the conflicts. I have a feeling that that would want claimid in the body but that would be another ticket.

2023-04-18 16:29 UTC, au2 commented on service/provider/src/main/java/gov/va/vro/service/provider/services/ExamOrderSlackProcessor.java
> +  public static String getSlackMessage(ExamOrdersInfo exams) {
why is this public?

2023-04-18 16:29 UTC, au2 commented on api/src/main/java/gov/va/vro/api/resources/ClaimMetricsResource.java
> +          Integer size);
Add the param added in PR 1664

2023-04-18 16:29 UTC, au2 commented on service/provider/src/main/java/gov/va/vro/service/provider/services/ExamOrderSlackProcessor.java
> +public class ExamOrderSlackProcessor implements Processor {
Do we really need this processor? Why don't you prepare the body before entering to the camel route and just enter with that one?

2023-04-19 16:07 UTC, ianwolson commented
Refactor and conflict resolution completely broke this :/  will continue trying to fix this.

2023-04-19 16:34 UTC, ianwolson commented
Nevermind, starting fresh on a new branch.  This one is hopeless.

2023-04-19 17:39 UTC, closed without merging