MCP-2661: Exam order info enhancement
department-of-veterans-affairs/abd-vro pull request #1446
Opened 2023-04-11 20:37 UTC by jbregstone

## What was the problem?

We need to be able too see which claims have do not have an exam ordered.

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

Adds a parameter for returning only exam info objects without an exam ordered. 

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-04-12 14:46 UTC, ianwolson approved these changes

2023-04-14 20:25 UTC, au2 requested changes
See inline. We should also have some JPA based unit tests with H2. Mockito will get you only so far for testing functionality.

2023-04-14 20:25 UTC, au2 commented on service/db/src/main/java/gov/va/vro/service/db/ClaimMetricsServiceImpl.java
> +    List<ExamOrderInfoResponse> response;
Use JPA not manual filtering. Paging will not work right the way you are doing either. findByOrderAtIsNull should work I believe.

2023-04-17 15:50 UTC, jbregstone commented
> See inline. We should also have some JPA based unit tests with H2. Mockito will get you only so far for testing functionality.

Could the JPA based unit tests with H2 be added in a separate PR?

I put in the JPA querying, not completely sure about the Paging issue. I wanted to keep the existing functionality the same (which uses a Page). I changed the new version use a List.

2023-04-17 17:31 UTC, jbregstone commented
End2end test failures seem to be unrelated, also happening on remote develop branch,
```
- gov.va.vro.end2end.VroV1Tests::positive7101Case01()
- gov.va.vro.end2end.VroV1Tests::positive6602Case01()
- gov.va.vro.end2end.VroV2Tests::testAutomatedClaimFullPositiveDuplicateBloodPressures()
```

2023-04-18 15:48 UTC, au2 approved these changes
Read the requirement again. We need to add another query parameter for dates I think. But I will add another ticker.

2023-04-18 15:48 UTC, merged