MCP-2730 Claim-Metrics getHealthEvidence
department-of-veterans-affairs/abd-vro pull request #1447
Opened 2023-04-11 20:47 UTC by ianwolson

## What was the problem?

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-04-12 01:53 UTC, au2 requested changes
v2/health-data-assessment was not as useful because it uses the v1 logic and do not include conditions. if possible switch to what v2 assessment uses.

2023-04-12 14:10 UTC, hayleymdawson commented on api/src/main/java/gov/va/vro/api/resources/ClaimMetricsResource.java
> +          "This endpoint does the same thing v2/health-data-assessment used to do. "
we probably need to support v2 and v1 through the same endpoint.

2023-04-12 14:11 UTC, hayleymdawson commented on controller/src/main/java/gov/va/vro/controller/ClaimMetricsController.java
> +      model.setIdType(MasAutomatedClaimPayload.CLAIM_V2_ID_TYPE);
can we repeat the pattern of default to v2, ask for v1? I will confirm with Yoom today about removing the other two endpoints.

2023-04-13 18:07 UTC, hayleymdawson commented on app/src/test/java/gov/va/vro/controller/VroControllerTest.java
> +  //  @Test
v1 endpoint has to be untouched so this needs to come back. Which may impact needing a default in the HealthAssessment Request.

2023-04-13 18:08 UTC, hayleymdawson commented on controller/src/main/java/gov/va/vro/controller/ClaimMetricsController.java
> +        MasAutomatedClaimPayload.builder()
There should be a mapper, but maybe it isn't accessible from here? if not, i'd put in a tech debt ticket about it and i can take a look next week.

2023-04-13 18:09 UTC, hayleymdawson commented on service/provider/src/main/java/gov/va/vro/service/provider/camel/PrimaryRoutes.java
> +  public static final String ENDPOINT_GET_HEALTH_EVIDENCE = "direct:get-health-evidence";
This looks to be unused (and should be unused?)

2023-04-13 18:10 UTC, hayleymdawson requested changes
Remove Primary Route changes if they aren't used (if they are, let me know why as I'm not seeing it).
Bring back v1 tests and the v1 endpoint has to merge.

Logic for the new mas integration route looks good to me, but obviously afsin will need to chime in.

2023-04-13 18:13 UTC, hayleymdawson commented on api/src/main/java/gov/va/vro/api/resources/ClaimMetricsResource.java
> +  ResponseEntity<HealthDataAssessment> healthEvidence(
Also i'm not sure if the HDA object here has everything we want. you may need FullHealthDataAssessmentResponse instead to expose the sufficientEvidence flag.

2023-04-19 20:11 UTC, ianwolson commented
Closing and making fresh PR here https://github.com/department-of-veterans-affairs/abd-vro/pull/1487

2023-04-19 20:11 UTC, closed without merging