Preliminary solution to 1594->create bip service
department-of-veterans-affairs/abd-vro pull request #1684
Opened 2023-06-14 08:49 UTC by engineer-plus-plus

The preliminary solution to [this story](https://github.com/department-of-veterans-affairs/abd-vro/issues/1594)

## What was the problem?
BIP api is just a bunch of classes that have no way of interacting with it.

Associated tickets or Slack threads:
all associated things are listed in [this story](https://github.com/department-of-veterans-affairs/abd-vro/issues/1594)

## How does this fix it?[^1]
Adds dependencies and annotations that cause it to listen to messages in rabbit mq.  Adds configuration to stand it up in a docker container.

## How to test this PR
Same way as in `svc-lighthouse-api`

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-06-20 15:42 UTC, engineer-plus-plus commented on svc-lighthouse-api/build.gradle
> +//test {
Not to self: this has to be uncommitted.

2023-06-20 20:55 UTC, yoomlam requested changes

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/build.gradle
> +  id 'jacoco'
You probably don't need these
```suggestion
```

2023-06-20 20:55 UTC, yoomlam commented on domain-rrd/gradle.properties
> +
```suggestion
```

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/build.gradle
> +  }
I don't think these are needed for BIP
```suggestion
```

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/src/docker/docker-compose.yml
Delete this file, unless there's a particular reason for it.

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/src/main/resources/application.properties
> +abd-data-access.rabbitmq.claim-submit-routing-key=code.#
`abd-data-access` was/is used for the `svc-lighthouse-api` client. Use something else like `bip-api-client`.

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/src/main/java/gov/va/vro/bip/config/RabbitMqConfig.java
> +  private String claimSubmitRoutingKey;
Shouldn't these settings and variable names correspond to the queues mentioned in `BipApiService`?

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/src/main/resources/application.properties
> +server.port=8091
```suggestion
```

2023-06-20 20:55 UTC, yoomlam commented on svc-bip-api/src/main/resources/application.properties
> +lh.pemkey=${LH_PRIVATE_KEY}
```suggestion
```

2023-06-27 16:06 UTC, engineer-plus-plus commented
closing pull request as the final solution will use a different model (svc-xample-j)

2023-06-27 16:06 UTC, closed without merging