1677: Create End to End BIE Kafka Integration Test
department-of-veterans-affairs/abd-vro pull request #1837
Opened 2023-07-21 23:07 UTC by dfitchett

## What was the problem?

There was no end to end test from mock kafka --> svc-bie-kafka --> xample-workflow --> postgres.

Associated tickets or Slack threads:
- #1677 
- #1680

## How does this fix it?[^1]

Adds continuous integration test.

## How to test this PR
- Run [continuous integration test](https://github.com/department-of-veterans-affairs/abd-vro/actions/workflows/continuous-integration.yml).

## Follow On:
This test should be updated if the `event_details` column in the table `claims.bie_contention_event` is updated. See [V1.1__BIE_Contention_Event.sql](https://github.com/department-of-veterans-affairs/abd-vro/blob/6b6b2ea72a949d7aaf9653319a7024be1eb102d2/db-init/src/main/resources/database/migrations/V1.1__BIE_Contention_Event.sql) and [ContentionEventEntity.java](https://github.com/department-of-veterans-affairs/abd-vro/blob/6b6b2ea72a949d7aaf9653319a7024be1eb102d2/shared/persistence-model/src/main/java/gov/va/vro/persistence/model/ContentionEventEntity.java) which may have been updated by #1680 

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-07-21 23:10 UTC, dfitchett commented on .github/workflows/bie-kafka-end2end-test-with-mock.yml
> +  TEST_DATA: 'Lorem ipsum'
This value is used as the `event_details` column saved in the DB.

2023-07-24 05:41 UTC, msnwatson approved these changes

2023-07-24 14:02 UTC, yoomlam requested changes

2023-07-24 14:02 UTC, yoomlam commented on mocks/docker-compose.yml
> +      - "9094:9094"
Add code comment describing the purpose of exposing this port.

2023-07-24 14:02 UTC, yoomlam commented on .github/workflows/continuous-integration.yml
> +  bie-kafka-end-to-end-mock:
```suggestion
  bie-kafka-end-to-end:
```

2023-07-24 15:52 UTC, yoomlam approved these changes
Great! Need to explain the Kakfa internal and external comms a bit more.

2023-07-24 16:29 UTC, yoomlam commented on mocks/docker-compose.yml
> +    # listeners are configured to consume messages on both ports.
Nice!

2023-07-24 16:59 UTC, merged