Mock Schema Registry
department-of-veterans-affairs/abd-vro pull request #2037
Opened 2023-09-18 16:55 UTC by chengjie8

## What was the problem?
There's no mock schema registry in place to conduct local testing using avro schema serialization/deserialization 

Associated tickets or Slack threads:
- #1902 

## How does this fix it?[^1]

## How to test this PR

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-09-25 23:12 UTC, msnwatson requested changes
Please be sure to add to the dependabot.yml file with the location of this new Dockerfile because there is a limitation where dependabot cannot recursively search for dockerfiles to keep track of updates.

Also, since we are adding a new container, it might be worth linking a successful SecRel run to be sure we are not introducing any new vulnerabilities from the base image.

2023-09-26 16:53 UTC, chengjie8 commented
> Please be sure to add to the dependabot.yml file with the location of this new Dockerfile because there is a limitation where dependabot cannot recursively search for dockerfiles to keep track of updates.
> 
> Also, since we are adding a new container, it might be worth linking a successful SecRel run to be sure we are not introducing any new vulnerabilities from the base image.

Sounds good. I will do that.

2023-10-03 16:52 UTC, chengjie8 commented
[latest scan has been completed here](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/6395504338) did not bring up additional issues. @msnwatson

2023-10-03 19:04 UTC, tejans24 reviewed
Do the current Kafka tests needed to be updated to utilize the Mock schema registry?

2023-10-03 19:04 UTC, tejans24 commented on mocks/mock-bie-schema-registry/build.gradle
> +  // copySpec.from("src/main/resources").into(".")
commented code here

2023-10-03 19:04 UTC, tejans24 commented on svc-bie-kafka/src/main/resources/application-integration-test.yaml
> +#        trust-store-type: "PKCS12"
should these lines be removed?

2023-10-17 21:00 UTC, msnwatson approved these changes

2023-10-27 17:31 UTC, chengjie8 commented on svc-bie-kafka/src/main/resources/application-integration-test.yaml
> +#        trust-store-type: "PKCS12"
reverted back, it was for testing

2023-10-30 15:44 UTC, tejans24 approved these changes
LGTM

2023-10-30 15:46 UTC, merged