Fetch claims endpoint
department-of-veterans-affairs/abd-vro pull request #217
Opened 2022-08-16 17:27 UTC by ianwolson

MCP-1620

## Description

### What was the problem?

na

### How does this fix it?

Fetch claims endpoint:  Returns claim submission ID, veteran ICN, and list of contention diagnostic codes for each claim.

### Jira Tickets

- [MCP-1620](https://amida.atlassian.net/browse/MCP-1620)

## How to test this PR

-Make mock data in db, veteran, then claim, then contentions.
-Make sure foreign keys line up (veteranID goes into claim, and claimID goes into contentions)
-Go to swagger and try out the fetch-claims endpoint.
-Verify that claim submission ID, veteran ICN, and list of contention diagnostic codes appear.
                                        

## Reminders

- Review [Pull-Requests](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests) guidelines
- [ ] If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) and
[Roadmap](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Roadmap) wiki pages
- [ ] If changing software behavior, post a link to the PR in Slack channel #benefits-virtual-regional-office

2022-08-16 21:28 UTC, wlin2019 approved these changes
I haven't tested it. It may not return the correct claims. See comments. Other than that, it looks good to me.

2022-08-16 21:28 UTC, wlin2019 commented on service/db/src/main/java/gov/va/vro/service/db/FetchClaimsServiceImpl.java
> +        String contention = (claimEntity.getContentions().get(i).getDiagnosticCode());
what is the parentheses for?

2022-08-16 21:28 UTC, wlin2019 commented on service/db/src/main/java/gov/va/vro/service/db/FetchClaimsServiceImpl.java
> +    SimpleClaim claim = new SimpleClaim();
Should this be moved into the for loop?

2022-08-25 16:29 UTC, dimitri-amida requested changes
Almost there. Just a few more comments

2022-08-25 16:29 UTC, dimitri-amida commented on api/src/main/java/gov/va/vro/api/model/ClaimInfo.java
> +  public String claimSubmissionId;
all these should be private

2022-08-25 16:29 UTC, dimitri-amida commented on app/src/test/java/gov/va/vro/FetchClaimsTest.java
> +    assert response != null;
This should be junit 5 assertNotNull

2022-08-25 16:29 UTC, dimitri-amida commented on controller/src/main/java/gov/va/vro/controller/VroController.java
> +    List<SimpleClaim> claimList = new ArrayList<>();
the list should not be initialized

2022-08-25 16:29 UTC, dimitri-amida commented on service/db/src/main/java/gov/va/vro/service/db/FetchClaimsServiceImpl.java
> +    List<ClaimEntity> claimList = new ArrayList<>();
The list should not be initialized. It can all be in one line 
List<ClaimEntity> claimList =claimRepository.findAll();

2022-08-25 16:29 UTC, dimitri-amida commented on service/spi/src/main/java/gov/va/vro/service/spi/model/SimpleClaim.java
> +public class SimpleClaim {
There is no need for a new POJO  class. Use ClaimMapper to convert from Entity to Claim. Then convert from Claim to ClaimInfo

2022-08-29 16:47 UTC, closed without merging