Declare exchanges/queues independent from client (fix #2152)
department-of-veterans-affairs/abd-vro pull request #2185
Opened 2023-11-03 21:28 UTC by raudabaugh

## What was the problem?
Users could not declare queues or exchanges without creating a publisher/consumer client.

Associated tickets or Slack threads:
- #2152 

## How does this fix it?[^1]

Creates a new class called `Channel` that works similarly to the queue client classes, but does not declare an exchange/queue upon connection startup.
### Usage
```python
channel = Channel()
await channel.connect()
channel.exchange_declare(exchange_properties=ExchangeProperties())
channel.queue_declare(queue_properties=QueueProperties())
```
Queues are automatically bound to an exchange upon creation.
This PR also refactors the `BaseQueueClient` class significantly, breaking off related functionality into separate base classes: `BaseChannelOpener`, `BaseExchangeDeclarer`, and `BaseQueueDeclarer`, allowing for more control over triggering certain callbacks.

## How to test this PR
- run `pytest` in `shared/lib-hoppy`

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-11-08 18:58 UTC, dfitchett requested changes
If some of the tests require RabbitMQ to be running, they should prob be moved to an integration folder. Also, with the updates to the RabbitMQ user/password from moving the image to bitnami. The `config.py` should be updated with those defaults.

2023-11-08 20:05 UTC, nanotone commented
@raudabaugh Would you mind bringing this branch up-to-date with your concurrency improvement changes in `main`? I'm seeing some repeat LOC changes in the diff.

2023-11-09 14:58 UTC, raudabaugh commented
@dfitchett @nanotone thanks for the feedback. This is ready for another look!

2023-11-09 16:54 UTC, dfitchett requested changes

2023-11-09 16:54 UTC, dfitchett commented on shared/lib-hoppy/pyproject.toml
I'm having trouble running the `pip install .` since there multiple top level packages besides `test`. So in order to install successfully, I think we just need to add the lines:
```
[tool.setuptools]
packages = ["hoppy"]
```

2023-11-09 18:46 UTC, dfitchett approved these changes
LGTM

2023-11-13 21:44 UTC, nanotone approved these changes
The code all looks good! ✨ And I'm in favor of a refactor that separates out all the different levels of RabbitMQ concepts.

2023-11-14 19:39 UTC, merged