Introduce annotations to handle the fields exclusive to only certain kafka topic names
department-of-veterans-affairs/abd-vro pull request #2368
Opened 2023-12-16 04:55 UTC by chengjie8

## What was the problem?
Currently, we try to fetch all field values in `BieMessagePayload` class from `GenericRecord`. Due to some fields that are not commonly shared from all kafka topics we listen to, it causes exceptions when the `GenericRecord` does not have the field value available.

Associated tickets or Slack threads:
- #2366 

## How does this fix it?[^1]
Introduced 2 new annotations
- `@Ignore` - mark fields that should be ignored when fetching from a GenericRecord.
- `@TargetEvents` - is used to define a field that is exclusive to certain contention classification events. Valid values are derived from the topic names in the ContentionEvent enum.

## How to test this PR
- Run unit and integration tests

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-12-21 20:54 UTC, agile-josiah requested changes
Other than the if statement LGTM

2023-12-21 20:54 UTC, agile-josiah commented on svc-bie-kafka/src/main/java/gov/va/vro/services/bie/utils/BieMessageUtils.java
> +          invokeSetterMethod(payload, field, genericRecord);
Is the if statement still needed? It seems like the if else is calling the same method and everything else is inconsequential/for logging.

2023-12-27 18:21 UTC, agile-josiah approved these changes

2023-12-27 18:21 UTC, agile-josiah commented on svc-bie-kafka/src/main/java/gov/va/vro/services/bie/utils/BieMessageUtils.java
> +          invokeSetterMethod(payload, field, genericRecord);
Ah that makes sense. LGTM then

2024-01-03 20:00 UTC, tejans24 approved these changes
LGTM

2024-01-03 20:07 UTC, merged