SD Elements: Docker Non Root User
department-of-veterans-affairs/abd-vro pull request #262
Opened 2022-09-07 13:01 UTC by anthonyvelazquez

# SD Elements: Docker Non Root User 

## Description

### What was the problem?

`root` is used by default for all the Dockerfile commands

### How does this fix it?

Create a new non root user to comply with SD Elements request

2022-09-08 00:44 UTC, au2 requested changes
1) You need to fix all the Dockerfiles (including the java ones). Should not be much different. If you want to do those in another pr that is fine too.
2) Please fix the checks. build-docker-images is failing. Something to do with python version.

2022-09-08 15:11 UTC, jbregstone approved these changes
I will approve but I did not try running as a rootless user

2022-09-08 16:55 UTC, au2 requested changes

2022-09-08 16:55 UTC, au2 commented on service-data-access/src/docker/Dockerfile
>  CMD ["sh", "entrypoint.sh"]
We are only adding the user? I thought we needed to switch to the user as well?

2022-09-08 16:55 UTC, au2 commented on app/src/docker/Dockerfile
> +RUN adduser -m docker
Only adding user? Shouldn't we switch as well?

2022-09-09 13:42 UTC, au2 approved these changes
@anthonyvelazquez  I think we should return an error when there is no content but I do not think it will ever go to that line so will let it go. For future I would identify if that line is ever reached always return error when there is no content.

2022-09-09 19:35 UTC, au2 requested changes
I meant to approve the other pr which I did. This still needs the inline comments addressed.

2022-09-14 22:10 UTC, au2 approved these changes
End points are working. Moving this.

2022-09-14 22:10 UTC, merged