Mcp 1808
department-of-veterans-affairs/abd-vro pull request #272
Opened 2022-09-09 16:53 UTC by ianwolson

# Feature Name 

## Description

### What was the problem?

### How does this fix it?

### Jira Tickets

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How to test this PR

- Step 1
- Step 2 

## Reminders

- Review [Pull-Requests](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests) guidelines
- [ ] If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) and
[Roadmap](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Roadmap) wiki pages
- [ ] If changing software behavior, post a link to the PR in Slack channel #benefits-virtual-regional-office

2022-09-09 18:02 UTC, jbregstone requested changes
This looks great! There's still one checkStyle violation, I will have to make a change in the python code as well. We should `asthma_relevant` camelCase, like `asthmaRelevant`. 

[ant:checkstyle] [WARN] /Users/julianbregstone/abd-vro/api/src/main/java/gov/va/vro/api/model/AbdMedication.java:20:19: Member name 'asthma_relevant' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MemberName]
Checkstyle rule violations were found. See the report at: file:///Users/julianbregstone/abd-vro/api/build/reports/checkstyle/main.html
Checkstyle files with violations: 1
Checkstyle violations by severity: [warning:1]

2022-09-09 19:15 UTC, jbregstone approved these changes

2022-09-09 20:24 UTC, anthonyvelazquez commented
Wait to merge until we update the same code on the PDF side as well

2022-09-12 13:07 UTC, rajesh-Krishnasamy approved these changes

2022-09-12 16:17 UTC, au2 commented
@ianwolson Can you resolve the conflict and move please

2022-09-12 17:11 UTC, merged