Externalize credentials - Mcp-1816
department-of-veterans-affairs/abd-vro pull request #296
Opened 2022-09-15 16:12 UTC by wlin2019

Using environment variables for username and password, and updating the project

## Description

1. Replace the credentials with environment variables. MCP-1816
2. Remove opa subproject as it is not used.3. 3. MCP-1858

The code change is based the code in branch MCP-1816 and MCP-1819 that Dimitri worked on. Since the current develop has changed quite a bit, the code merge has problems. This code change (PR) leaves out two things that seem to be addressed in MCP-1819. 1) admin account for RabbitMQ. 2) Some Postgres/Flyway related setting. See comments in MCP-1816

### What was the problem?

For security, the credentials should not be hard coded. opa sub project has no use in this project.

### How does this fix it?

Use the environment variables for credentials, and remove unused code.

### Jira Tickets

MCP-1816, MCP-1819, MCP-1858

## How to test this PR

- Step 1: Get updated setevn.sh and private.pem from abd-vro-dev-secretes and copy them to the project build directory.
- Step 2: Run setenv.sh.
- Step 3: Follow the README to build the application.

## Reminders

- Review [Pull-Requests](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests) guidelines
- [ ] If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) and
[Roadmap](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Roadmap) wiki pages
- [ ] If changing software behavior, post a link to the PR in Slack channel #benefits-virtual-regional-office

2022-09-15 19:04 UTC, au2 requested changes
Please take a look at other places. One place we hit is application-compose.yml

2022-09-15 20:52 UTC, wlin2019 commented on app/src/docker/docker-compose.yml
Good catch! They got merged out. Put them back now.

2022-09-15 20:53 UTC, wlin2019 commented on app/src/docker/docker-compose.yml
> +      RABBITMQ_PLACEHOLDERS_USERPASSWORD: ${RABBITMQ_PASSWORD}
Changed the names, and updated in setenv.sh in secrets repo as well.

2022-09-15 21:16 UTC, wlin2019 commented on app/src/docker/docker-compose.yml
>      volumes:
I'm reluctant to do this as "vro" is also used in url. But anyway, I created an env var, POSTGRES_DBNAME, for it (It is also used as POSTGRES_DBNAME in the project).

2022-09-16 02:47 UTC, au2 requested changes
Added one more inline comment.

2022-09-16 02:47 UTC, au2 commented on app/src/main/resources/application-compose.yml
>        jdbc-url: jdbc:postgresql://vro-api-postgres-service:5432/vro
Please put the url in an environment variable here and add it to docker-compose. Maybe POSTGRES_URL.

2022-09-16 09:56 UTC, au2 requested changes
Please add 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_PLACEHOLDERS_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PLACEHOLDERS_USERPASSWORD}
to docker-compose. This will give us a quick ability to change default rabbit user.

2022-09-16 12:56 UTC, merged