MCP-1873 PDF Generator Error Reason Field
department-of-veterans-affairs/abd-vro pull request #332
Opened 2022-09-21 12:56 UTC by anthonyvelazquez

#MCP-1873 PDF Generator Error Reason Field 

## Description

- PDF Generator was still returning a 200 even though we got a `status: ERROR`
- PDF Generator now adds a `reason` field in addition to the `status: ERROR` to give a better description of what went wrong

### Jira Tickets

- [MCP-1873](https://amida.atlassian.net/browse/MCP-1873)

## How to test this PR

- Turn off Redis container and generate a PDF. Status should be `500` and you should see a `reason`

2022-09-22 01:05 UTC, au2 requested changes
A test calling generate pdf is failing.

2022-09-23 02:15 UTC, au2 requested changes
@anthonyvelazquez I put a fix for the test in branch MCP-1873-Fix, please take a look. Essentially the test is erroneous, results in 500 but expects 200. Since we are returning 200 before for errors, it was passing. Now it is failing. It actually turned out to be a good before and after  test for this pr. In MCP-1873-Fix I put proper input and also return proper output from the mock route.

2022-09-26 10:33 UTC, au2 approved these changes

2022-09-26 13:03 UTC, anthonyvelazquez commented
![image](https://user-images.githubusercontent.com/13013464/192146007-1ed3780a-6c0a-413c-8192-5f5e683e21cd.png)

2022-09-26 13:03 UTC, ianwolson approved these changes

2022-09-26 14:10 UTC, merged