MCP-1924 Python Consumer Updates
department-of-veterans-affairs/abd-vro pull request #459
Opened 2022-10-03 22:47 UTC by anthonyvelazquez

# MCP-1924 Python Consumer Updates 

## Description

Added more details on how the consumer works as well as a check to see if the connection was established before trying to close it

2022-10-04 14:07 UTC, au2 requested changes
Inline comments

2022-10-04 14:07 UTC, au2 commented on service-python/main_consumer.py
>          self.setup_queues()
Still calling this if self.connection is None. If I see self.connection to be None in garbage collection it can be None here too.

2022-10-04 14:07 UTC, au2 commented on service-python/main_consumer.py
>              consumer = RabbitMQConsumer(CONSUMER_CONFIG)
This I do not understand. Suppose _create_connection failed in all tries (so self.connection is None)? What then? the consumer will not be None and we will happily call start_consuming?

2022-10-06 13:38 UTC, anthonyvelazquez commented
Script now checks if the connection is not `None` in the class creation as well as in the runtime loop, it checks if **channel** is not `None` as well

2022-10-06 13:53 UTC, jbregstone approved these changes

2022-10-07 14:26 UTC, au2 requested changes
@anthonyvelazquez last two changes.

2022-10-07 14:26 UTC, au2 commented on service-python/main_consumer.py
>                  logging.warning(f"RabbitMQ Connection Failed. Retrying in 30s ({i + 1}/{self.config['retry_limit']})")
One more thing. Can we add information about the exception here? Looks like logging.warning has a exc_info parameter where you can specify the exception instance.

2022-10-07 14:26 UTC, au2 commented on service-python/main_consumer.py
> +            del consumer
Please put a logging warning here for the exception.  Looks like logging.warning has a exc_info parameter where you can specify the exception instance.

2022-10-07 17:41 UTC, au2 approved these changes
Some of the exceptions still not what I expect but we have messages now and it appears that the service recovers from rabbit errors so approving. We can do another round later.

2022-10-07 17:41 UTC, merged