Change error code for missing evidence from 404 to 500
department-of-veterans-affairs/abd-vro pull request #726
Opened 2022-11-21 14:51 UTC by jbregstone

## What was the problem?

Associated tickets or Slack threads:

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How does this fix it?[^1]

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2022-11-21 17:16 UTC, anthonyvelazquez approved these changes

2022-11-21 18:48 UTC, au2 requested changes
You need to change controller code. That is the real problem. Also this is an internal error not No Evidence found.

2022-11-21 19:36 UTC, jbregstone commented
> 

Is there any more information on the error? It's a python exception?

2022-11-26 02:45 UTC, au2 approved these changes
Most done already hotfixes are merged back.  Approving this for now. We need to correct these descriptions anyway.

2022-11-26 02:45 UTC, merged