MCP-2087: Add date and time to python logging messages
department-of-veterans-affairs/abd-vro pull request #759
Opened 2022-12-01 17:10 UTC by jbregstone

## What was the problem?

No way to see when messaged were processed by python condition service. 
Associated tickets or Slack threads:

- [MCP-2087](https://amida.atlassian.net/browse/MCP-2087)

## How does this fix it?[^1]

Adds date and time to logging
## How to test this PR
- Step 1 Build and run app.
- Step 2 Send request with full-health endpoint. Looks at docker logs and see that message has a date and time. 
- [^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2022-12-01 17:23 UTC, jbregstone commented
> LGTM except is there a reason for the `flake8` downgrade?

It has been causing build problems for me. It says pip can't find it. It could be the version of pip, maybe in another PR we can try to upgrade pip before installing requirements.

2022-12-01 21:01 UTC, anthonyvelazquez approved these changes

2022-12-05 18:10 UTC, au2 requested changes
1) We need this in all python services. Including pdf generator.
2) I would look into logging formatter and do that way instead of manually doing it for each logging line. Better yet you can share between all micro-services. I think we are already sharing some code somewhere. Maybe some common library?
3) Please add a brief description to your branch names.

2022-12-14 01:42 UTC, au2 approved these changes
Works as expected. Maybe we should read level from a config file but that is for future.

2022-12-14 01:42 UTC, merged