MCP-2137 Add sufficientEvidence flag to claims.
department-of-veterans-affairs/abd-vro pull request #899
Opened 2023-01-04 22:14 UTC by ianwolson

MCP-2137 Add sufficientEvidence flag to claims.

## What was the problem?
We need to add a sufficient evidence flag to claims after MAS automated claim processes the claims.

Associated tickets or Slack threads:

- [MCP-2137](https://amida.atlassian.net/browse/MCP-2137)

## How does this fix it?[^1]

## How to test this PR
- Step 1 run health assessment endpoint with claimSubmissionId 1234.
- Step 2 run MAS automated claim endpoint, make sure claimSubmissionId is the same as benefitClaimId.
- Step 3 check the claim in the VRO db for the correct flag, [] = false and [v] = true.

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-01-06 01:18 UTC, au2 requested changes
I am assuming we should follow what we did for version 1 path and move this flag to contentions. I was under the impression that database was designed for multiple contentions per claim for future multiple issue claims. Either way this is a assesment result item not claim since it is being produced by assessment,

2023-01-26 18:37 UTC, dimitri-amida commented
@ianwolson in latest development, I created MasAssessmentResultProcessor. I think this is the best place to update the sufficiency flag, at the same time as inserting the assessment.

2023-02-02 21:37 UTC, wlin2019 approved these changes
I'm not familiar with the data model used, and the flow of setting up this flag. I have no objection to merge this PR. But here's some concerns.
1. I feel the DB update logic might be a bit too complicated. But if the data model is set that way, it probably won't be able to find a much better solution.
2. It doesn't seem have proper consideration for error handling.

2023-02-02 21:37 UTC, wlin2019 commented on service/db/src/main/java/gov/va/vro/service/db/SaveToDbServiceImpl.java
> +      log.warn("Could not find claim with given claimSubmissionId.");
Is it considered as a problem if the claim is not found? If yes, should it be handled other than just logging here?

2023-02-02 21:37 UTC, wlin2019 commented on service/provider/src/main/java/gov/va/vro/service/provider/services/MasAssessmentResultProcessor.java
> +    saveToDbService.updateSufficientEvidenceFlag(
It looks like that the two variables created here don't do much. Just using evidence get methods in next line can reduce a couple of lines.

2023-02-13 05:23 UTC, au2 commented
@ianwolson is this pr still alive or are the new developments are taken over?

2023-02-14 16:08 UTC, closed without merging