Mcp 2009 - update BIP API Service
department-of-veterans-affairs/abd-vro pull request #910
Opened 2023-01-07 04:17 UTC by wlin2019

Update BIP Claims and Evidence API services.

## What was the problem?
The current BIP API service code is not used in the application due to the conflict with the testing. As we updated the environment based building, the conflict is resolved. So this PR enacts the BIP API service. 

BIP Controller is provided for testing some BIP api services. At present, there are five endpoints. The controller used to work with a mocking service in VRO code.  This PR changes it.

1. It is using this mocking service when the app is build in local (default) environment. 
2. It is using an outside mocking service, when it is in dev environment. To build a dev environment, set environment variable ENV=dev.
3. When deploying it in VRO dev environment, set the environment variables by run setuatenv.sh in secret repo in addition to setenv.sh. It will change the BIP service URL to BIP UAT environment. 4. 

Note: 3 out of the five endpoints in BIP Controller are not working at present. The endpoint was broken on Dec 19 when Lombok got updated. 

Associated tickets or Slack threads:
MCP-2009

## How does this fix it?[^1]

## How to test this PR
- Step 1. Follow the normal process to build the app.
- Step 2. Go to the swagger page, test get claim and get contention endpoints.
- Step 3. Set ENV to dev, export ENV=dev. Rebuild and launch the application.
- Step 4. Repeat step 2, using claim ID, 9729039.
- Step 5. run source ./setuatenv.sh (get setuatenv.sh from secret repo). Rebuild and launch the application.
- Step 6. Repeat step 4, you'll see "Name does not resolve" error as you are out side VA network.

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

2023-01-09 14:25 UTC, rajesh-Krishnasamy approved these changes

2023-01-09 14:34 UTC, dimitri-amida requested changes
Local deployment on docker fails:

2023-01-09 06:29:58 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bipCERestTemplate' defined in class path resource [gov/va/vro/config/BipApiConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.client.RestTemplate]: Factory method 'getHttpsRestTemplate' threw exception; nested exception is gov.va.vro.service.provider.bip.BipException: Failed to create SSL context.

2023-01-10 15:58 UTC, au2 commented
@dimitri-amida I can deploy the app locally. Maybe run scripts/setenv.sh?

2023-01-10 19:28 UTC, au2 approved these changes
Local is still working and the end point responds as expected. Moving

2023-01-10 19:30 UTC, dimitri-amida approved these changes

2023-01-10 19:38 UTC, merged